<?php

/**
 * @var \Dtn\Cosmetic\Block\ProductInfo $block
 */
$convertedAttributeValue = $block->getCurrentProduct();

$ingredientModel = $block->getModel();
$ingredientResource = $block->getResourceModel();
?>
<?php

if ($block->getAttributeSet() == 15) { //Check if not be attribute set id ingredient cosmetic then hide detail product tab ingredient in front end
    ?>
    <p><?php foreach ($convertedAttributeValue as $value) {
            $value = json_decode($value);
            $ingredientResource->load($ingredientModel, $value);
            $modelData = $ingredientModel->getData();
            $img = json_decode($modelData['img'])[0]->name;
            ?>
            <img style="width: 150px ; height: 150px"
                 src="https://magento242.local/media/ingredientImg/<?php echo $img; ?>">
            <?
        }
        ?>
    </p>
    <?php
}
?>